-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here

-- local augroup = vim.api.nvim_create_augroup("alpha_on_empty", { clear = true })
--
-- vim.api.nvim_create_autocmd("user", {
--   group = augroup,
--   pattern = "BDeletePost*",
--   callback = function(event)
--     local fallback_name = vim.api.nvim_buf_get_name(event.buf)
--     local fallback_ft = vim.api.nvim_buf_get_option(event.buf, "filetype")
--     local fallback_on_empty = fallback_name == "" and fallback_ft == ""
--
--     if fallback_on_empty then
--       require("nvim-tree").close_all()
--       vim.cmd("Dashboard")
--       vim.cmd(event.buf .. "bwipeout")
--     end
--   end,
-- })
